// Import mongoose to define schemas and interact with MongoDB
const mongoose = require('mongoose');

// Define the schema for a single subtopic
const subtopicSchema = new mongoose.Schema({
  // Name of the subtopic (e.g., Addition, Multiplication)
  name: {
    type: String,
    required: true,     // Name must be provided
    trim: true          // Removes spaces from the beginning and end
  },

  // Content related to the subtopic (e.g., explanation or lesson text)
  content: {
    type: String,
    default: ''         // Defaults to an empty string if no content is given
  },

  // Indicates whether the content was generated by AI or manually added
  generated: {
    type: Boolean,
    default: false      // Defaults to false (manually created)
  }
});

// Define the schema for a subject, which contains multiple subtopics
const subjectSchema = new mongoose.Schema({
  // Name of the subject (e.g., Math, Science)
  name: {
    type: String,
    required: true,     // Name must be provided
    trim: true,         // Remove extra spaces
    unique: true        // No two subjects can have the same name
  },

  // Short description of the subject
  description: {
    type: String,
    trim: true
  },

  // Optional image link for the subject (e.g., icon or banner)
  imageUrl: {
    type: String,
    default: ''         // Defaults to an empty string
  },

  // List (array) of subtopics that belong to this subject
  subtopics: [subtopicSchema]
}, { 
  // Automatically add createdAt and updatedAt timestamps
  timestamps: true
});

// Export the Subject model so it can be used in other files
module.exports = mongoose.model('Subject', subjectSchema);
